# multi_auth_sample
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MultiAuthSample
  # HttpCallBack allows defining callables for pre and post API calls.
  class HttpCallBack < CoreLibrary::HttpCallback
  end
end
