# multi_auth_sample
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MultiAuthSample
  # Utility class for custom query_parameter authorization.
  class ApiKey < CoreLibrary::QueryAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'ApiKey: token or api_key is undefined.'
    end

    # Initialization constructor.
    def initialize(api_key_credentials)
      auth_params = {}
      auth_params['token'] = api_key_credentials.token unless
        api_key_credentials.nil? || api_key_credentials.token.nil?
      auth_params['api-key'] = api_key_credentials.api_key unless
        api_key_credentials.nil? || api_key_credentials.api_key.nil?

      super auth_params
    end
  end

  # Data class for ApiKeyCredentials.
  # Data class for ApiKeyCredentials.
  class ApiKeyCredentials
    attr_reader :token, :api_key

    def initialize(token:, api_key:)
      raise ArgumentError, 'token cannot be nil' if token.nil?
      raise ArgumentError, 'api_key cannot be nil' if api_key.nil?

      @token = token
      @api_key = api_key
    end

    def clone_with(token: nil, api_key: nil)
      token ||= self.token
      api_key ||= self.api_key

      ApiKeyCredentials.new(token: token, api_key: api_key)
    end
  end
end
