# multi_auth_sample
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MultiAuthSample
  # Utility class for custom authorization.
  class CustomAuth < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      # TODO: Add your error message here in case of failure in authentication
      #
      # Example:
      # 'CustomAuth: config.access_token is undefined.'
    end

    # Initialization constructor.
    def initialize(config)
      auth_params = {}

      # TODO: Add your custom authentication here
      # The following properties are available to use
      # auth_params['accessToken'] = config.access_token

      super auth_params
      @_config = config
    end

    # Validate arguments for authentication.
    # @return [Boolean] true if the auth parameters are present.
    def valid
      # TODO: Add your validation checks here
      #
      # Example:
      # return false unless @_config.access_token.nil?
      true
    end
  end
end
