# multi_auth_sample
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
require 'json'
require 'apimatic_core_interfaces'
require 'apimatic_core'
require 'apimatic_faraday_client_adapter'
# rubocop:disable Style/MixinUsage
include CoreLibrary
# rubocop:enable Style/MixinUsage

require_relative 'multi_auth_sample/api_helper'
require_relative 'multi_auth_sample/client'

# Utilities
require_relative 'multi_auth_sample/utilities/file_wrapper'
require_relative 'multi_auth_sample/utilities/date_time_helper'

# Http
require_relative 'multi_auth_sample/http/http_call_back'
require_relative 'multi_auth_sample/http/http_method_enum'
require_relative 'multi_auth_sample/http/http_request'
require_relative 'multi_auth_sample/http/http_response'
require_relative 'multi_auth_sample/http/auth/basic_auth'
require_relative 'multi_auth_sample/http/auth/api_key'
require_relative 'multi_auth_sample/http/auth/api_header'
require_relative 'multi_auth_sample/http/auth/o_auth_ccg'
require_relative 'multi_auth_sample/http/auth/o_auth_acg'
require_relative 'multi_auth_sample/http/auth/o_auth_ropcg'
require_relative 'multi_auth_sample/http/auth/o_auth_bearer_token'
require_relative 'multi_auth_sample/http/auth/custom_auth'

# Models
require_relative 'multi_auth_sample/models/base_model'
require_relative 'multi_auth_sample/models/service_status'
require_relative 'multi_auth_sample/models/user'
require_relative 'multi_auth_sample/models/o_auth_token'
require_relative 'multi_auth_sample/models/suite_code_enum'
require_relative 'multi_auth_sample/models/o_auth_provider_error_enum'
require_relative 'multi_auth_sample/models/o_auth_scope_o_auth_acg_enum'

# Exceptions
require_relative 'multi_auth_sample/exceptions/api_exception'
require_relative 'multi_auth_sample/exceptions/o_auth_provider_exception'

require_relative 'multi_auth_sample/configuration'

# Controllers
require_relative 'multi_auth_sample/controllers/base_controller'
require_relative 'multi_auth_sample/controllers/authentication_controller'
require_relative 'multi_auth_sample/controllers/o_auth_authorization_controller'
