# multi_auth_sample
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MultiAuthSample
  # API utility class
  class APIHelper < CoreLibrary::ApiHelper
  end
end
