# multi_auth_sample
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MultiAuthSample
  # OAuth 2 scopes supported by the API
  class OAuthScopeOAuthACGEnum
    O_AUTH_SCOPE_O_AUTH_ACG_ENUM = [
      # Read request for files
      READ_SCOPE = 'file_requests.read'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      O_AUTH_SCOPE_O_AUTH_ACG_ENUM.include?(value)
    end
  end
end
